2.03 add new tag element
IATI/IATI-Schemas pull request #369
Opened 2017-11-14 12:05 UTC by allthatilk

2017-11-14 12:09 UTC, hayfield commented
PR should have a description.

2017-11-14 12:25 UTC, dalepotter commented
Just had a quick look at this whilst adding test cases for namespace elements and attributes.

There needs to be test cases for `tag/narrative` too - I will mark as incomplete and add these shortly.

2017-11-14 16:05 UTC, dalepotter commented
is there any `should-fail` test that could be applied to `iati-activities/iati-activity/tag/@vocabulary-uri` ?
 The datatype is marked as `xsd:anyURI`.

2017-11-14 16:21 UTC, hayfield commented
`xsd:anyURI` is very permissive https://www.w3.org/TR/xmlschema-2/#anyURI

> Because it is impractical for processors to check that a value is a context-appropriate URI reference, this specification follows the lead of [RFC 2396] (as amended by [RFC 2732]) in this matter: such rules and restrictions are not part of type validity and are not checked by ·minimally conforming· processors. Thus in practice the above definition imposes only very modest obligations on ·minimally conforming· processors.

2017-11-16 16:09 UTC, dalepotter commented
We're defining `<xsd:element ref="tag" minOccurs="0" maxOccurs="unbounded"/>`, so I would suggest adding a `should-pass` test case for 2 `tag` elements.

2017-11-23 11:01 UTC, hayfield requested changes

2017-11-23 11:01 UTC, hayfield commented on iati-activities-schema.xsd
> +        Categorisations from established taxonomies that enrich the
Scout's honour. Rapping.

2017-11-23 11:01 UTC, hayfield commented on tests/should-fail/iati-activities/iati-activity/tag/err-not-iati-xml-missing-attribute.xml
> +    <iati-identifier></iati-identifier>  <!-- 1 and only 1-->
Lots of comments like this that should be removed.

Will do a more thorough look once comments are removed (it's hard to do when they're there!)

2017-11-28 10:38 UTC, dalepotter commented
Marking this as `incomplete` for the time being, pending line wrapping change.

2017-11-28 10:51 UTC, dalepotter commented on iati-activities-schema.xsd
> +        Categorisations from established taxonomies that enrich the
Fixed in fd0e247.

2017-11-28 11:10 UTC, dalepotter approved these changes

2017-11-28 11:10 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/tag/element-exists-with-required-and-optional-attributes.xml
> +  <iati-activity> <!-- at least 1 -->
These pesky comments still there - grrr...

2017-11-28 11:55 UTC, hayfield commented on tests/should-fail/iati-activities/iati-activity/tag/err-not-iati-xml-missing-attribute.xml
> +    <iati-identifier></iati-identifier>  <!-- 1 and only 1-->
6be59361a38f36b706476abc63a4b30f516afd31

2017-11-28 11:57 UTC, hayfield approved these changes

2017-11-29 11:32 UTC, merged