Add test data for baseline/dimension addition, make schema refactor a…
IATI/IATI-Schemas pull request #374
Opened 2017-11-15 12:34 UTC by allthatilk

…nd addition.

2017-11-16 09:28 UTC, hayfield commented on iati-activities-schema.xsd
> +        age, etc.
Mid-sentence hard-wrapping

2017-11-23 10:52 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-all-attributes.xml
> +    <iati-identifier></iati-identifier>  <!-- 1 and only 1-->
According to the new docs format, we need to remove all these `<!-- 1 and only 1-->` comments

2017-11-23 10:53 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-all-attributes.xml
> +          <dimension name= "xx" value="xx"><!-- dimension element included with all possible attributes for elements -->
Comment should be prepended by `PASS:`

2017-11-23 11:07 UTC, dalepotter requested changes
Need to add tests for namespace elements and attributes, for example as done for changes to `iati-activity/result/reference` [here](https://github.com/IATI/IATI-Schemas/blob/3cae387909fb2987d89e1e12b3462185de80b8b2/tests/should-pass/iati-activities/iati-activity/result/reference/reference-element-present-with-namespace-attribute.xml#L25) for an attribute and [here](https://github.com/IATI/IATI-Schemas/blob/3cae387909fb2987d89e1e12b3462185de80b8b2/tests/should-pass/iati-activities/iati-activity/result/reference/reference-element-present-with-namespace-element.xml#L25-L27) for an element.

(NOTE: You need to add the namespace declaration to `iati-activity` for this to work - [example here](https://github.com/IATI/IATI-Schemas/blob/3cae387909fb2987d89e1e12b3462185de80b8b2/tests/should-pass/iati-activities/iati-activity/result/reference/reference-element-present-with-namespace-attribute.xml#L3))

Suggested test cases here would be:

```
<baseline year="2017" value= "xx">
   <dimension name= "xx" value="xx" example-namespace:namespace-attribute="xx"/><!-- PASS: ADD COMMENT HERE :-) -->
<baseline>
```

and 

```
<baseline year="2017" value= "xx">
   <dimension name= "xx" value="xx">
      <example-namespace:namespace-element></example-namespace:namespace-element><!-- PASS: ADD COMMENT HERE :-) -->
   </dimension>
<baseline>
```

2017-11-23 11:07 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-all-attributes.xml
> +    <iati-identifier></iati-identifier>  <!-- 1 and only 1-->
Same for other test case files.

2017-11-23 11:07 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-all-attributes.xml
> +          <dimension name= "xx" value="xx"><!-- dimension element included with all possible attributes for elements -->
Same for other test case files.

2017-11-23 11:07 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-all-attributes.xml
> +          <dimension name= "xx" value="xx"><!-- dimension element included with all possible attributes for elements -->
Suggest `possible attributes` -> `optional attributes`.

2017-11-23 11:07 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-value-attribute.xml
> +<?xml version="1.0"?>
Suggest this test is moved to `...iati-activity/result/indicator/baseline/dimension/_value/element-exists-with-value-attribute.xml`

2017-11-23 11:07 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/dimension/element-exists-with-name-attribute.xml
> +<?xml version="1.0"?>
Suggest this test is moved to `...iati-activity/result/indicator/baseline/dimension/_name/element-exists-with-value-attribute.xml`

2017-11-23 12:18 UTC, dalepotter approved these changes
Nice!

2017-11-23 12:34 UTC, merged