2.03 add location to results baseline
IATI/IATI-Schemas pull request #378
Opened 2017-11-16 12:57 UTC by allthatilk

Fixes #365

2017-11-23 11:20 UTC, dalepotter commented
Suggest review awaits merging of #377.

2017-11-27 10:09 UTC, hayfield commented
#377 now merged

2017-11-27 10:11 UTC, hayfield requested changes

2017-11-27 10:11 UTC, hayfield commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/location/element-exists.xml
> +          <location></location><!-- optional location element included -->
Suggest noting in the comment that an optional attribute is missing.

2017-11-27 10:11 UTC, hayfield commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/location/element-exists.xml
> +  <iati-activity> <!-- at least 1 -->
Misc comments to remove

2017-11-28 11:54 UTC, hayfield commented
Flipping label since I forgot to do that with the review.

2017-11-29 11:04 UTC, hayfield approved these changes

2017-11-29 11:11 UTC, merged