2.03 update#350
IATI/IATI-Schemas pull request #386
Opened 2017-11-28 12:05 UTC by allthatilk

Fixes #350

2017-11-28 12:19 UTC, hayfield requested changes
Suggest that all changes related to `aid-type` go into an integration branch.

#345 #346 #350 

This PR will likely require changes based on the other PRs.

2017-11-29 10:51 UTC, allthatilk commented
@hayfield done. Please re-review.

2017-11-29 10:55 UTC, hayfield approved these changes

2017-11-29 10:56 UTC, hayfield commented
Base branch changed.

Approving, though it'll need noting that additional tests for this will need adding in the other PRs. This should be noted somewhere obvious for anybody reviewing the other changes.

2017-11-29 11:06 UTC, merged