2.03 update#353
IATI/IATI-Schemas pull request #392
Opened 2017-11-29 16:17 UTC by allthatilk

Fixes the schema aspects of #353

2017-12-05 12:10 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/_value/attribute-exists.xml
> +        <baseline year="2017" value= "xx"><!-- PASS: optional attribute included once -->
Remove whitespace for consistency: `value= "xx"` -> `value="xx"`

2017-12-05 12:12 UTC, dalepotter requested changes
Small thing on whitespace...

2017-12-05 12:13 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/_iso-date/attribute-does-not-exist.xml
> +        <baseline year="2017" value= "xx"><!-- PASS: optional iso-date attribute not included -->
Also here: `value= "xx"` -> `value="xx"`

2017-12-05 12:13 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/result/indicator/baseline/_iso-date/attribute-exists-for-element-correct-date-format.xml
> +        <baseline year="2017" value= "xx" iso-date="2017-11-16"><!-- PASS: optional iso-date attribute included using correct datetime format -->
Also here: `value= "xx"` -> `value="xx"`

2017-12-06 10:56 UTC, allthatilk commented
@dalepotter ready for rereview =)

2017-12-06 14:35 UTC, dalepotter approved these changes
Looks good!

2017-12-06 15:39 UTC, merged