2.03 update#346
IATI/IATI-Schemas pull request #402
Opened 2017-12-01 12:52 UTC by allthatilk

Fixes #346 for schema

2017-12-05 11:02 UTC, dalepotter requested changes
One small thing re naming of the attribute.

Otherwise looks good :1st_place_medal:

2017-12-05 11:02 UTC, dalepotter commented on iati-activities-schema.xsd
> +  <xsd:attribute name="vocabulary" type="xsd:string">
`vocabulary` is a commonly-used term, so would suggest naming this `aidTypeVocabulary`.

2017-12-05 11:02 UTC, dalepotter commented on tests/should-pass/iati-activities/iati-activity/default-aid-type/_vocabulary/attribute-exists.xml
> +    <reporting-org type="xx" ref="xx"><narrative>Organisation name</narrative></reporting-org>
For info, I've added an issue to fix the formatting of this line en masse before release: https://github.com/IATI/IATI-Schemas/issues/403

2017-12-06 14:54 UTC, allthatilk commented
@dalepotter ready for rereview

2017-12-06 15:50 UTC, dalepotter requested changes
One thing on the naming of the `complexType`.

2017-12-06 15:50 UTC, dalepotter commented on iati-activities-schema.xsd
> +  <xsd:complexType name="aid-type-base">
I think we tend to name `complexType`s using lower camel case  - e.g. in https://github.com/IATI/IATI-Schemas/pull/372/files#diff-644a12e8a6ade95722e1f3adf60b7462R148

2017-12-06 16:12 UTC, allthatilk commented
@dalepotter ready for rerereview

2017-12-06 17:20 UTC, dalepotter approved these changes
Looks good!

2017-12-06 18:02 UTC, merged